### ISSUE TITLE
Why was options.duplicate/inputTree copy removed? 

### ISSUE THREAD

**Issue by jayphelps** [rwjblue/broccoli-file-mover#12]
When [this](https://github.com/rwjblue/broccoli-file-mover/commit/0cb3a0403066b6d97cd434f3b3cc658a87258cca) was merged, it removed the default behavior of keeping the other files in the `inputTree` and didn't keep it as a feature either.

How it was before IMO seemed like the natural, expected behavior which [many](https://github.com/tildeio/router.js/blob/master/Brocfile.js#L147) [people](https://github.com/jamesarosen/ember-cpm/blob/f2787b08b819ec716b71a7ce2e00e99c86e9e971/Brocfile.js#L17) [depended](https://github.com/alexdiliberto/form-autofill/blob/a8308a0cc2ee672f44de784a762a4bb8e872be1c/Brocfile.js#L16) on in previous versions.

Just curious why it was completely removed. AFAIK if you want the same behavior as before, after doing `moveFile` you remove the original file from the `inputTree` then merge the two together, right?

**Comment by kanongil** [comment]
@rwjblue Can we get a clarification on this? You seem to depend on the duplicate behavior yourself (or at least forget that it was removed).

**Comment by rwjblue** [comment]
Yeah, I can't remember why I removed it.  Seems really stupid now.

**Comment by jayphelps** [comment]
^^^ LOL

You told me on IRC long a go, but I forgot as well.

**Comment by rwjblue** [comment]
broccoli-file-mover is now deprecated in favor of using broccoli-funnel.

broccoli-funnel allows you to both filter, and change paths for any file (in the same step).  It also supports include and exclude patterns (as RegExps).

https://github.com/rwjblue/broccoli-file-mover/commit/90a64c248762ecd0cfc8d4f7d9be4bc39a1cd45f
