### ISSUE TITLE
Directory coming along with specific files

### ISSUE THREAD

**Issue by tonywok** [rwjblue/broccoli-file-mover#4]
I'm trying to do the following:

``` js
var emberApp = app.toTree();

var customFonts = moveFile('vendor', {
  files: {
    'entypo/font/entypo.eot' : 'webfonts/entypo.eot',
    'entypo/font/entypo.ttf' : 'webfonts/entypo.ttf',
    'entypo/font/entypo.woff': 'webfonts/entypo.woff',
    'entypo/font/entypo.svg' : 'webfonts/entypo.svg'
  }
});

module.exports = mergeTrees([emberApp, customFonts], {overwrite: true});
```

The ember-cli app builds, but it moves all of vendor into `/dist` in the process. Am I using the `broccoli-file-mover` api correctly? I'm just trying to copy a handful of files into `dist/webfonts/`

Apologies in advance if this is on my end. Thanks for the lib! :) See you in the ember-cli issues.

**Comment by rwjblue** [comment]
By default, this will return a tree with all of the input tree and the files specified moved to the new location. If you want the returned tree to ONLY contain the files you specify you must specify `copy: false` to prevent the rest of the input tree from being copied.

**Comment by tonywok** [comment]
@rjackson hmm, I switched it to `copy: false`, but the files are still being copied into `dist`. Does it have something to do with `mergeTrees`?

**Comment by orlaqp** [comment]
I have a similar issue while trying to copy the font-awesome's fonts directory. Any solution to yet?
