### ISSUE TITLE
Option to skip `readTree()` call to support large dirs of uninteresting files

### ISSUE THREAD

**Issue by ericf** [rwjblue/broccoli-file-mover#5]
It would be great to add an option to skip the `readTree()` call — which causes the Broccoli watcher to watch everything in that dir — and only copy/link the files explicitly listed.

The `broccoli-bower` package [does this](https://github.com/joliss/broccoli-bower/blob/master/index.js#L8-12) because watching a dir like `bower_components/` or `node_modules/` is very resource intensive and unlikely to change.

In my case I want to pluck only a couple files out of my `node_modules/` dir to copy them to a dir I serve assets to the client so I can reuse that code. When doing this operation where the `node_modules/` input tree gets passed to the `readTree()` function, my CPU went up to 40% because the watcher was having to do _tons_ of work.

I ended up [writing this](https://github.com/yui/pure-site/blob/master/lib/map-files.js) (note how I don't invoke `readTree()`), but felt this sort of "un-watch" option could be part of this package instead. What do you think?

**Comment by rwjblue** [comment]
@ericf - Thank you for writing up the issue! I have had similar problems, and dealt with it similarly. 

I have extracted the `UnwatchedTree` into a standalone package, and submitted PR's upstream to both `broccoli-bower` and `ember-cli`.  

References:

https://github.com/rjackson/broccoli-unwatched-tree
https://github.com/joliss/broccoli-bower/pull/7
https://github.com/stefanpenner/ember-cli/pull/693

The solution in your scenario would be to use `broccoli-unwatched-tree` as the input tree (will work for nearly _any_ plugin also):

``` javascript
var unwatchedTree = require('broccoli-unwatched-tree');

var bowerComponents = unwatchedTree('bower_components');
```

**Comment by ericf** [comment]
Sweet, sounds good. I'll do that and switch to using your plugins to gain the caching and linking features they have.
